// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9g9LACShd-R8dzQ2UyEEectz1epRU1sg',
    appId: '1:996462654002:web:6aa27a687aa9e8fc45022b',
    messagingSenderId: '996462654002',
    projectId: 'khabrak-99bd5',
    authDomain: 'khabrak-99bd5.firebaseapp.com',
    storageBucket: 'khabrak-99bd5.firebasestorage.app',
    measurementId: 'G-YE79D084E5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoD4A5BsjLpifH50hpluY3gIdGgdht_WI',
    appId: '1:996462654002:android:373fd3f209688bb945022b',
    messagingSenderId: '996462654002',
    projectId: 'khabrak-99bd5',
    storageBucket: 'khabrak-99bd5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBioa9--ngOKVewkCDpdAe95wht8CbDH30',
    appId: '1:996462654002:ios:00bc2c20fd62d05945022b',
    messagingSenderId: '996462654002',
    projectId: 'khabrak-99bd5',
    storageBucket: 'khabrak-99bd5.firebasestorage.app',
    iosBundleId: 'com.example.khabark',
  );
}
